### ISSUE TITLE
Make src/main/csharp the default source directory

### ISSUE THREAD

**Issue by zosrothko** [codehaus-plexus/plexus-compiler#100]
Hello

Currently, the plexus-csharp-compile is taking `src/main/java` as the default source directory. Making src/main/csharp the default directory would let csharp compiling phase activated within a profile by 
```
<profile>
	<id>csharp-comp</id>
	<activation>
		<file>
			<exists>${basedir}/src/main/csharp</exists>
		</file>
	</activation>
</profile>
```
instead of
```
<profile>
	<id>csharp-comp</id>
	<activation>
		<file>
			<exists>${basedir}/src/main/java</exists>
		</file>
	</activation>
</profile>
```
which is  misnamed

**Comment by olamy** [comment]
we can't change that as it's part of Maven core itself.
TBH not sure you will be able to convince someone to change that :)

**Comment by zosrothko** [comment]
> we can't change that as it's part of Maven core itself.
Can you explain a little bit? because I am planning to extend the plexus-compiler with a cobol adapter that will pickup its sources in `src/main/cobol` as default source directory.
