### ISSUE TITLE
Adding additional CompilerConfiguration causes integration test to fail 

### ISSUE THREAD

**Issue by bondolo** [codehaus-plexus/plexus-compiler#115]
I am working on adding a showLint option to maven-compiler-plugin (https://issues.apache.org/jira/browse/MCOMPILER-442)

When I add a get/setShowLint() members to CompilerConfiguration the simple-javac test fails due to:

```
491:[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project simple-javac: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile: java.lang.NoSuchMethodError: 'java.lang.String org.codehaus.plexus.compiler.CompilerConfiguration.getShowLint()'
493:[ERROR] realm =    plugin>org.apache.maven.plugins:maven-compiler-plugin:3.8.1
495:[ERROR] urls[0] = file:/Users/mike/code/maven/plexus-compiler/plexus-compiler-its/target/local-repo/org/apache/maven/plugins/maven-compiler-plugin/3.8.1/maven-compiler-plugin-3.8.1.jar
```

As the 3.8.1 compiler does not know about this option. When build skipping tests and install the plexus-compiler API 3.8.9-SNAPSHOT and then build a maven compiler plugin 3.9.0-SNAPSHOT which uses the plexus-compiler API 3.8.9-SNAPSHOT I can execute the tests by using that version in `plexus-compiler-its/src/main/it/simple-javac/pom.xml` but the circularity is problematic.

@olamy How can I introduce a new CompilerConfiguration without breaking the integration tests?

**Comment by bondolo** [comment]
ping @olamy

**Comment by olamy** [comment]
what about adding this in the ITs pom
```
          <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-compiler-api</artifactId>
            <version>@pom.version@</version>
          </dependency>
```

**Comment by bondolo** [comment]
I will give that a try!

**Comment by bondolo** [comment]
The suggestion resolved the issue. Now present in PR#131
