### ISSUE TITLE
"release" parameter should only be set for javac version >= 9

### ISSUE THREAD

**Issue by kwin** [codehaus-plexus/plexus-compiler#140]
Sometimes it is difficult to set up the plugin configuration in a way to support different JDKs (maybe even using toolchains). For example look at [MPOM-264](https://issues.apache.org/jira/browse/MPOM-264). To ease that the JavacCompiler should only use the `-release` parameter with [version 9](https://docs.oracle.com/javase/9/tools/javac.htm#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9__GUID-D343F6B4-3FDD-43A8-AD24-43DD70214471) or above as using it with [earlier versions](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html) leads to errors.

An additional condition should be added to https://github.com/codehaus-plexus/plexus-compiler/blob/0a0aab0b8ef16ea91460ff9878877137e5ddc2bc/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L344

**Comment by rfscholte** [comment]
This should be done at maven-compiler-plugin level, to ensure that every compiler implementation gets the same set of arguments. The more I think about it, the more it looks like https://issues.apache.org/jira/browse/MCOMPILER-270 from almost 5 years ago.
Reading the conclusion I still agree with myself: using the release flag should be a choice of the project, it should not be calculated as there are situation where you don't want to use the release flag. As long as the compiler supports source/target it must be possible to pass it as is.

**Comment by kwin** [comment]
IMHO plexus-compiler and m-compiler-p is a higher level abstraction and therefore should try to translate the intent of the parameter into the compiler specific flags. Release is clearly a parameter for javac >= 9 but does mot make sense for earlier versions nor for some other compilers.

**Comment by slachiewicz** [comment]
a lot of code in JavacCompiler related to Java < 8 can be deleted

**Comment by rfscholte** [comment]
> a lot of code in JavacCompiler related to Java < 8 can be deleted

I don't think so. Keep in mind that you can still use toolchain, and best practice is to use the targeted JDK to compile.

**Comment by kwin** [comment]
There is already https://github.com/codehaus-plexus/plexus-compiler/blob/0a0aab0b8ef16ea91460ff9878877137e5ddc2bc/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L370 which implements the same logic for parameter `source` (only supported in javac 1.4 or newer).
