### ISSUE TITLE
Support --process-module-path

### ISSUE THREAD

**Issue by rfscholte** [codehaus-plexus/plexus-compiler#150]
It is possible to have both `--process-module-path` and `--process-path`, so the configurationConfiguration should support both options. Thsi is similar to the separation of classpath and modulepath, where e.g. the maven-compiler-plugin is responsible for dividing the jars over both paths.

**Comment by cowwoc** [comment]
Either the parameter name change or there is a typo in the title and description. I think you meant to refer to `--processor-module-path` not `--process-module-path`.
