### ISSUE TITLE
Introduce Compiler.supportsIncrementalCompilation

### ISSUE THREAD

**Issue by rfscholte** [codehaus-plexus/plexus-compiler#154]
With this hint the caller can decide which classes should be (re)compiled. In general if incremental compilation is not supported, it is best to recompile everything if something has changed.
(Since Compiler is an interface, this requires Java 8 so a default method can be added)

**Comment by rfscholte** [comment]
Warning: it is a boolean, but it should have been an integer to define which parts are supported. Don't use the boolean flag! Sadly 
 the library was released before this could be fixed.

**Comment by olamy** [comment]
I don;t understand? you pushed that here https://github.com/codehaus-plexus/plexus-compiler/commit/7476614bc15e6f706820dd74be2c97eab7efb350
we can change that as not sure it's really used for now and it's a very recent release

**Comment by rfscholte** [comment]
This was indeed the first approach, but later I discovered that it is not a simple true/false thingy, It must be more finegrained.
