### ISSUE TITLE
Don't create `javac.[sh|bat]` or `org.codehaus.plexus.compiler.javac.JavacCompiler*arguments` in `target/*classes`

### ISSUE THREAD

**Issue by zregvart** [codehaus-plexus/plexus-compiler#165]
When debug logging is turned on Javac Plexus compiler creates two additional files in `target/classes` or `target/test-classes`. These files will be also included in the built artifact, say a JAR file.

This is done here:

https://github.com/codehaus-plexus/plexus-compiler/blob/f4103632269e7a3ae0c7a78aafab48b88f941386/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L597-L598

And here:

https://github.com/codehaus-plexus/plexus-compiler/blob/f4103632269e7a3ae0c7a78aafab48b88f941386/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L991-L992

Seems that the calls to `config.getOutputLocation()` need to be replaced with `config.getBuildDirectory()` in those two instances.

**Comment by urld** [comment]
I second that. I would expect the same resulting package regardless of whether debugging is enabled or not.
Leaving those files in target/classes can also causes build failures in debug mode when maven-duplicate-finder-plugin is used.

**Comment by zregvart** [comment]
Thanks for resurrecting this discussion @urld, I've proposed a change in #173 that I think will fix this issue. Feedback welcome!
