### ISSUE TITLE
Advanced options plexus-compiler-j2objc

### ISSUE THREAD

**Issue by vicmosin** [codehaus-plexus/plexus-compiler#17]
I need somehow to set `--no-package-directories` flag, but can't find how to do that with plugin definition.

Provided example of 

```
<compilerArguments>
   <use-arc />
   <sourcepath>src/main/java</sourcepath>
</compilerArguments>
```

doesn't allow it because of `--` (double minus sign)

Using of 

```
<compilerArgs>
   <arg>-use-arc</arg>
   <arg>-sourcepath src/main/java</arg>
   <arg>-d target/objc</arg>
   <arg>-x objective-c</arg>
   <arg>--no-package-directories</arg>
</compilerArgs>
```

fails with `The argument -sourcepath src/main/java isnt't a flag recognized by J2ObjC.`

**Comment by rfscholte** [comment]
AFAIK you should make 2 arguments of it, i.e.

    <arg>-sourcepath</arg>
    <arg>src/main/java</arg>

**Comment by vicmosin** [comment]
@rfscholte Due to https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#compilerArgs - nope

**Comment by rfscholte** [comment]
I have to check, but I would expect that every whitespace starts a new argument.

**Comment by vicmosin** [comment]
Then this check https://github.com/codehaus-plexus/plexus-compiler/blob/master/plexus-compilers/plexus-compiler-j2objc/src/main/java/org/codehaus/plexus/compiler/j2objc/J2ObjCCompiler.java#L224 will fail, what basically happens)

**Comment by rfscholte** [comment]
https://github.com/codehaus-plexus/plexus-compiler/blob/master/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L345 has another approach, which might fit better here too.

**Comment by vicmosin** [comment]
yes.. since we don't have any way to override the `config.getCustomCompilerArguments` behavior
