### ISSUE TITLE
Can't compile using compiler-eclipse with maven

### ISSUE THREAD

**Issue by abenz1267** [codehaus-plexus/plexus-compiler#176]
Hi,

my pom.xml for the maven compiler plugin looks like this:
```
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.8.1</version>
 <configuration>
    <compilerId>eclipse</compilerId>
    <source>1.8</source>
    <target>1.8</target>
    <encoding>UTF-8</encoding>
</configuration>
<dependencies>
    <dependency>
        <groupId>org.codehaus.plexus</groupId>
       <artifactId>plexus-compiler-eclipse</artifactId>
       <version>2.8.1</version>
    </dependency>
</dependencies>
```

But running `mvn clean verify` results in following error: `MYFILE:[57] System cannot be resolved`

I've simply followed the instructions [here](https://maven.apache.org/plugins/maven-compiler-plugin/non-javac-compilers.html)

Any idea why the compiler can't resolve `System`?

Regards

**Comment by olamy** [comment]
can we have a sample project?
