### ISSUE TITLE
javac compiler doesn't support `--processor-module-path`

### ISSUE THREAD

**Issue by ghost** [codehaus-plexus/plexus-compiler#53]
Maven builds fail if the following conditions are set:
- Using Java 9 or 10
- Using `module-info.java`
- Build depends on the execution of annotation processors (like Lombok)

This results in using the module path instead of the class path of the `javac` compiler. Now the `javac` compiler also needs to be configured with `--processor-module-path` so that the compiler can find the required annotation processors in the processor module path. The latest version of `plexus-compiler-javac` only supports the `--processorpath` parameter of `javac`. This parameter is set by the `maven-compiler-plugin` to the default class path. But when using Java 9+ modules the class path doesn't seem to be used by `javac` to find the annotation processors. So, to use annotation processors in combination with Java 9+ modules, the `plexus-compiler-javac` needs to support the related parameter.

**Comment by scholzi100** [comment]
I repoduce the problem with Java 12 too. `--processor-module-path` should be used with Java 9+ and only when a `module-info` file is created. 

_Hotfix: set all processors manually in the `annotationProcessors` section of `maven-compiler-plugin`._
