### ISSUE TITLE
[plexus-compiler-csharp] - unable to generate executable.

### ISSUE THREAD

**Issue by ethiclab** [codehaus-plexus/plexus-compiler#7]
Hello,

The following project is configured for compiling into a .NET executable, but it is not working properly since it always generates a dll.

https://github.com/ethiclab/example-csharp-maven-project-01

We have been working on a fix, please let us know if we can issue a pull request.

Our latest commit is:

https://github.com/ethiclab/plexus-compiler/tree/feature/fix-compiler-args

Thanks in advance,

Best,

EthicLab.

**Comment by olamy** [comment]
definitely worth a pr.
Thanks!

**Comment by montoyaedu** [comment]
Hi Olivier,

This problem is yet open. :(

Do you think is there any chance to have this PR merged?

https://github.com/codehaus-plexus/plexus-compiler/pull/8

Thanks,

Edu.
