### ISSUE TITLE
EclipseCompiler does not respect encoding.

### ISSUE THREAD

**Issue by karkusviktor** [codehaus-plexus/plexus-compiler#73]
Since 2.8.6 it reads the files with default charset:
https://github.com/codehaus-plexus/plexus-compiler/blob/0df7395b3922cffd043dd25b3d88875bf802e982/plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java#L328

Try compiling the attached file when default charset is ISO-8859-1.
[Utf.java.txt](https://github.com/codehaus-plexus/plexus-compiler/files/4624367/Utf.java.txt)

**Comment by tomaswolf** [comment]
As far as I see the BatchCompiler also would use the default charset. Did you mean that you'd compile this by giving the charset on the command-line? Or which charset should be used?

**Comment by tomaswolf** [comment]
I think this can be closed.

How about a new release? In addition to this, #78 also added support for the <release> tag.
